// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCms6KLS95SQg7AdgzEKoSmaf6G4kUmRhA',
    appId: '1:596536582871:web:d9026c35b7f09e5f5c8692',
    messagingSenderId: '596536582871',
    projectId: 'mu-career-path-e0576',
    authDomain: 'mu-career-path-e0576.firebaseapp.com',
    storageBucket: 'mu-career-path-e0576.firebasestorage.app',
    measurementId: 'G-6TNWBSP6RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABE5sYy0A9EQ93jSJjcTY-efverRPSvf4',
    appId: '1:596536582871:android:db1cb25f2098bada5c8692',
    messagingSenderId: '596536582871',
    projectId: 'mu-career-path-e0576',
    storageBucket: 'mu-career-path-e0576.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLV8nAo6IsA8QL2Rxad94TBatPp5Spp8w',
    appId: '1:596536582871:ios:46bd16709ee844fb5c8692',
    messagingSenderId: '596536582871',
    projectId: 'mu-career-path-e0576',
    storageBucket: 'mu-career-path-e0576.firebasestorage.app',
    iosBundleId: 'com.example.muCareerPath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLV8nAo6IsA8QL2Rxad94TBatPp5Spp8w',
    appId: '1:596536582871:ios:46bd16709ee844fb5c8692',
    messagingSenderId: '596536582871',
    projectId: 'mu-career-path-e0576',
    storageBucket: 'mu-career-path-e0576.firebasestorage.app',
    iosBundleId: 'com.example.muCareerPath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCms6KLS95SQg7AdgzEKoSmaf6G4kUmRhA',
    appId: '1:596536582871:web:06fd3f7340fa67445c8692',
    messagingSenderId: '596536582871',
    projectId: 'mu-career-path-e0576',
    authDomain: 'mu-career-path-e0576.firebaseapp.com',
    storageBucket: 'mu-career-path-e0576.firebasestorage.app',
    measurementId: 'G-JYH4S27F61',
  );
}
