import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

// Screens
import 'screens/auth_gate.dart';
import 'screens/login_screen.dart';
import 'screens/student_dashboard.dart';
import 'screens/admin_dashboard.dart';
import 'screens/edit_profile_screen.dart';
import 'screens/add_experience_screen.dart';
import 'screens/view_companies_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ✅ Initialize Firebase before running the app
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MUApp());
}

class MUApp extends StatelessWidget {
  const MUApp({super.key});

  static const Color muBlue = Color(0xFF002D72);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'MU Career Path',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primaryColor: muBlue,
        colorScheme: ColorScheme.fromSwatch().copyWith(secondary: muBlue),
        appBarTheme: const AppBarTheme(
          backgroundColor: muBlue,
          foregroundColor: Colors.white,
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: muBlue,
            foregroundColor: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
          ),
        ),
      ),

      // ✅ Set the first screen dynamically using Firebase Auth
      home: const AuthGate(),

      // ✅ Define all app routes
      routes: {
        '/login': (_) => const LoginScreen(),
        '/student': (_) => const StudentDashboard(),
        '/admin': (_) => const AdminDashboard(),
        '/edit_profile': (_) => const EditProfileScreen(),
        '/add_experience': (_) => const AddExperienceScreen(),
        '/companies': (_) => ViewCompaniesScreen(),
      },
    );
  }
}
